### ISSUE TITLE
Add product image next to the product name in Shopping cart

### ISSUE THREAD

**Issue by nikohoffren** [nikohoffren/hunajaholisti-website#2]
Add image of the product(s) next to the product name in Cart.tsx.

**Comment by vasfvitor** [comment]
I started this just to see If I'm capable as I don't have much experience with React and I noticed some issues.

The product image are too big to be displayed as an icon, perhaps in the future use a icon to represent each product. 

![image](https://github.com/nikohoffren/hunajaholisti-website/assets/61759797/542e866f-f852-47c6-bffa-3ebbcc3eeafe)

I placed some data from the product in a `productsData` object, mainly because I used the same src and alt text in the card. So if one changes the other will without having to edit both manually. I imagine in the future it should be in separated file with all the data for each product and then iterate a component over it in Products.tsx

I'm not sure this is the right approach. Any suggestions?

code: https://github.com/nikohoffren/hunajaholisti-website/compare/main...vasfvitor:hunajaholisti-website:cart-product-image

Lastly, the product isn't a component that one can add/remove/modify products easily. Not directly related to the current issue #2. I guess I could try to make a component out of it, at least to the card wrapper.

**Comment by nikohoffren** [comment]
> I started this just to see If I'm capable as I don't have much experience with React and I noticed some issues.
> 
> The product image are too big to be displayed as an icon, perhaps in the future use a icon to represent each product.
> 
> ![image](https://user-images.githubusercontent.com/61759797/260860953-542e866f-f852-47c6-bffa-3ebbcc3eeafe.png)
> 
> I placed some data from the product in a `productsData` object, mainly because I used the same src and alt text in the card. So if one changes the other will without having to edit both manually. I imagine in the future it should be in separated file with all the data for each product and then iterate a component over it in Products.tsx
> 
> I'm not sure this is the right approach. Any suggestions?
> 
> code: [main...vasfvitor:hunajaholisti-website:cart-product-image](https://github.com/nikohoffren/hunajaholisti-website/compare/main...vasfvitor:hunajaholisti-website:cart-product-image)
> 
> Lastly, the product isn't a component that one can add/remove/modify products easily. Not directly related to the current issue #2. I guess I could try to make a component out of it, at least to the card wrapper.

Yeah i agree, i definitely need to make some smaller icons for the product images. The way you have the images right now is fine though.

The `productsData` could also be in its own file as you said but that can be done in the future. Your approach looks good for now i think. I like the `productsData` object since it makes easier to add more products later on if they come up.

You can make a component out of it if you like, but i'm also fine with the solution as it is.
